---

- hosts: postgres #all
  become: true
  gather_facts: no
  roles:
   - { role: docker_role }
#   - { role: node_exporter_role }
#   - { role: cadvisor_role }

#- hosts: prometheus
#  become: true
#  gather_facts: no
#  roles:
#    - { role: prometheus_role }

#- hosts: pgadmin
#  become: true
#  gather_facts: no
#  roles:
#    - { role: web_role }

#- hosts: postgres
#  become: true
#  gather_facts: no
#  roles:
#    - { role: db_role }

...
