---
- name: Copy prometheus config file
  template:
     src: prometheus.yml.j2
     dest: prometheus.yml

- name: Copy file with prom container rules
  ansible.builtin.copy:
    src: container.rules
    dest: container.rules

- name: Copy file with prom host rules
  ansible.builtin.copy:
    src: host.rules
    dest: host.rules

- name: Run an prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    ports:
      - "80:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./container.rules:/etc/prometheus/container.rules"
      - "./host.rules:/etc/prometheus/host.rules"

- name: Copy alertmanager config file
  template:
     src: alertmanager.yml.j2
     dest: alertmanager.yml

- name: Run an alertmanager container
  docker_container:
    name: alertmanager
    image: prom/alertmanager
    restart_policy: unless-stopped
    restart: yes
    command: --config.file=/config/alertmanager.yml --log.level=debug
    ports:
     - "9093:9093"
    volumes:
      - "./alertmanager.yml:/config/alertmanager.yml"