---
- name: Copy prometheus config file
  template:
     src: prometheus.yml.j2
     dest: prometheus.yml

- name: Run an prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    ports:
      - "80:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

- name: Copy alertmanager config file
  template:
     src: alertmanager.yml.j2
     dest: alertmanager.yml

- name: Run an alertmanager container
  docker_container:
    name: alertmanager
    image: prom/alertmanager
    restart_policy: unless-stopped
    restart: yes
    command: --config.file=/home/{{ ansible_user }}/alertmanager.yml --log.level=debug
    ports:
     - "9093:9093"