---
- name: Run a node exporter container
  docker_container:
    name: node-exporter
    image: quay.io/prometheus/node-exporter
    network_mode: host
    pid_mode: host
    command:
      - '--path.rootfs=/host'
    ports:
      - "9100:9100"