---
- name: Install the latest version of node_exporter
  ansible.builtin.yum:
    name: node_exporter
    state: latest

- name: Enable node_exporter
  systemd:
    name:    node_exporter
    enabled: yes