---
- name: Install the latest version of Docker
  yum:
    name:  docker
    state: latest

- name: Start docker
  systemd:
    state:   started
    name:    docker
    enabled: yes

- name: Enable docker
  systemd:
    name:    docker
    enabled: yes

- name: Install docker python package
  ansible.builtin.pip:
    name: docker


